libTHTensor.0.dylib:
	clang -Ofast -msse4.2 -mfma -mavx -mavx2 -march=native -mtune=native -ffp-contract=fast -flto -framework Accelerate -c *.c vector/AVX.c vector/AVX2.c
	clang -shared -o libTHTensor.0.dylib *.o -framework Accelerate
